name: CI
on: [push, pull_request, workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      SKIP_MODEL_LOAD: "1"
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install deps
        run: pip install -r requirements.txt

      - name: Add repo root to PYTHONPATH
        run: echo "PYTHONPATH=$PWD" >> $GITHUB_ENV

      - name: Show env & deps
        run: |
          python -V
          echo "PYTHONPATH=$PYTHONPATH"
          ls -la
          find . -maxdepth 2 -name "main.py" -type f
          pip freeze | sed -n '1,80p'

      - name: Run tests (verbose)
        run: pytest -vv --maxfail=1 -rA